#script to deploy on the Render cloud platform

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: action/checkout@v2
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} #This is the GitHub token
        service-id: "srv-cg9dv2pmbg54mbeg0990" #This id is unique for each app
        retries: 20
        wait: 16000
        sleep: 30000
        
        
